In [3]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [4]:
print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)

(7,)
float64
7


In [7]:
temperatures_f = (temperatures_w1 * 9/5) + 32
print(temperatures_f)

print(temperatures_w1.max())
print(temperatures_w1.min())
print(temperatures_w1.mean())


[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
26.1
20.8
23.542857142857144


In [8]:
print(temperatures_w1[:3])
print(temperatures_w1[-2:])
print(temperatures_w1[2:5])

[22.5 25.3 20.8]
[24.8 21.9]
[20.8 23.4 26.1]


In [9]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

In [10]:
print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)

print(temperatures[0])
print(temperatures[1])
print(temperatures[:, -2:])

(2, 7)
float64
14
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[[24.8 21.9]
 [22.8 20.1]]


In [11]:
import pandas as pd

marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

In [12]:
print(marks[0])
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])
print(marks.iloc[2])
print(marks[marks > 90])

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_2698/3770611259.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [13]:
marks.loc['Rank1'] = 100
marks = marks.drop('Rank5')
cgpa = marks / 10

print(marks)
print(cgpa)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [14]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

In [15]:
print(transactions)
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [16]:
print(transactions[['ProductCategory', 'Amount']])
print(transactions.iloc[:, -3:])
print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])
print(transactions['ProductCategory'].value_counts())
print(transactions['Region'].unique())
print(transactions.groupby('Region')['Amount'].mean())

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

transactions['Discount'] = transactions['Amount'] * 0.10

transactions = transactions[transactions['TransactionID'] != 109]

transactions = transactions.drop(columns=['Discount'])

print(transactions)

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400
   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
['North' 'South' 'East' 'West']
Region
East     375.0
North    287